name: Build, Test, and Deploy

on:
    push:
        branches:
            - master
        paths-ignore:
            - 'samples/**'

    pull_request:
        branches:
            - master
env:
    # DOTNET_2_VERSION: 2.1.808
    # DOTNET_3_VERSION: 3.1.302
    DOTNET_5_VERSION: 5.0.100-preview.6.20318.15
    BUILD_CONFIGURATION: Release

jobs:
    build-test-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v1

            # - name: Setup .NET Core ${{ env.DOTNET_2_VERSION }}
            #   uses: actions/setup-dotnet@v1
            #   with:
            #       dotnet-version: ${{ env.DOTNET_2_VERSION }}

            # - name: Setup .NET Core ${{ env.DOTNET_3_VERSION }}
            #   uses: actions/setup-dotnet@v1
            #   with:
            #       dotnet-version: ${{ env.DOTNET_3_VERSION }}

            - name: Setup .NET Core ${{ env.DOTNET_5_VERSION }}
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ env.DOTNET_5_VERSION }}

            # - name: Setup side by side .NET SDKs on *nix
            #   if: matrix.os != 'windows-latest'
            #   run: |
            #       rsync -a ${DOTNET_ROOT/${{ env.DOTNET_5_VERSION }}/${{ env.DOTNET_3_VERSION }}/${{ env.DOTNET_2_VERSION }}}/* $DOTNET_ROOT/

            - name: Build
              run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }}

            - name: Unit Test
              run: dotnet test --configuration ${{ env.BUILD_CONFIGURATION }}

            - uses: aarnott/nbgv@v0.3
              with:
                  setAllVars: true

            - name: Pack
              run: dotnet pack --configuration ${{ env.BUILD_CONFIGURATION }}

            - name: Push to feedz.io
              run: dotnet nuget push **/*.nupkg -k ${{ secrets.FEEDZ_API_KEY }} -s https://f.feedz.io/forevolve/localization/nuget/index.json
              if: github.event_name == 'pull_request'

            - name: Push to NuGet.org
              run: dotnet nuget push **/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
              if: github.event_name == 'push'
